In [26]:
import torch

w = torch.tensor([[2, 3, 4]], dtype=torch.float32,requires_grad=True)
b = torch.tensor([3], dtype=torch.float32,requires_grad=True)
x = torch.tensor([[5, 2, 1]], dtype=torch.float32, requires_grad=True)
y = torch.tensor([7], requires_grad=True, dtype=torch.float32)

In [20]:
loss = ((x @ w.T + b) - y)**2

In [21]:
loss

tensor([[256.]], grad_fn=<PowBackward0>)

In [22]:
loss.backward()

In [23]:
w.grad

tensor([[160.,  64.,  32.]])

In [24]:
b.grad

tensor([32.])

In [28]:
optimizer.zero_grad()

AttributeError: 'Tensor' object has no attribute 'zero_grad'